name: Testes de API em PROD e mochawesome.

on:
  push:
    branches: [ master ]
  workflow_dispatch:
permissions: write-all

jobs:
  teste-de-api-em-serverest-dev:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3
    - name: Setup do Node.js
      uses: actions/setup-node@v3
    - name: Instalar as dependências do projeto
      run: npm ci  | 
           npm install -g allure-commandline --save-dev
    - name: Executar os testes de API
      run: npm run test.prod
      continue-on-error:  true
    - name: mostra as pastas
      run: ls -la
    - name: Publishing artifact to GitHub Actions
      uses: actions/upload-artifact@v3
      with:
        name: report
        path: report
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages  # default: gh-pages
        publish_dir: report
        destination_dir: report
